# Site Settings
title:               Numerical simulations blog
tagline:             by Slawomir Polanski
description:
baseurl:             /blog
url:                 https://spolanski.github.io
github:
  url:               https://spolanski.github.io/blog
author:
  name:              "Slawomir Polanski"
  email:             "polanski.slawomir@gmail.com"
  github:            "spolanski"
  linkedin:          "slawomirpolanski"
  twitter:           "_spolanski_"
  instagram:         "polanski.slawomir"
navigation:

- title: Categories
  url: /categories
- title: About me
  url: /about

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins_dir:         _plugins

picture:
  source: "assets/images"
  output: "assets/images/resize"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.2, 2.0]
      source_medium:
        media: "(min-width: 10em)"
        width: "800"
      source_default:
        width: "600"
